server:
  port: 8080
  Project : zzjy_urfs
  Server : http://192.168.0.48

#spring配置
spring:
  application:
    name: zzjy_urfs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/zzjy_urfs?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true
    username: hwzn
    password: Server@2023
  # 配置文件上传大小和总上传文件大小
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 5000MB

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:com.hwzn/mapper/*.xml
  type-aliases-package: com.hwzn.pojo.entity
  configuration:
    #驼峰命名
    mapUnderscoreToCamelCase: true
    #控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true


